version: '3'

services:
  portafolio:
    container_name: portafolio
    image: diegoasencio96/portafolio:0.0.1
    ports:
      - "8010"
    volumes:
      - portafolio-static:/app/portafolio/static
      - portafolio-resources:/app/portafolio/resources
      - portafolio-media:/app/portafolio/media

    environment:
      VIRTUAL_HOST: plants.diegoasencio.co
      VIRTUAL_PORT: 8010
      ENVIRONMENT: prod
      DB_NAME: portafolio_db
      DB_USER: convocat
      
volumes:
    portafolio-data:
    portafolio-static:
    portafolio-resources:
    portafolio-media:
networks:
  default:
    external:
      name: proxyssl_alcaldianetwork
