# Generated by Django 3.2.7 on 2021-09-25 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/category/', verbose_name='Imagen de la categoria')),
                ('name', models.CharField(blank=True, default='name', max_length=180, null=True, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/plants/', verbose_name='Imagen de la planta')),
                ('name', models.CharField(blank=True, default='name', max_length=180, null=True, verbose_name='Nombre comun')),
                ('scientific_name', models.CharField(blank=True, default='name scientific', max_length=180, null=True, verbose_name='Nombre cientifico')),
                ('description', models.TextField(blank=True, default='description', null=True, verbose_name='Descripción')),
                ('category', models.ForeignKey(blank=True, default='Category', null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.category', verbose_name='Categoria')),
                ('place', models.ManyToManyField(to='plants.Place', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'PLanta',
            },
        ),
    ]
